CREATE DATABASE IF NOT EXISTS taster_db;
USE taster_db;

CREATE TABLE IF NOT EXISTS Accounts (
    ID VARCHAR(255) PRIMARY KEY,
    DisplayName VARCHAR(100) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Events (
    ID VARCHAR(255) PRIMARY KEY,
    HostID VARCHAR(255) NOT NULL,
    Title VARCHAR(100) NOT NULL,
    Type VARCHAR(100) NOT NULL,
    State VARCHAR(100) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Participants (
    ID VARCHAR(255) PRIMARY KEY,
    EventID VARCHAR(255) NOT NULL,
    AccountID VARCHAR(255),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EventID) REFERENCES Events(ID),
    FOREIGN KEY (AccountID) REFERENCES Accounts(ID)
);

ALTER TABLE Events
ADD FOREIGN KEY (HostID) REFERENCES Participants(ID);

CREATE TABLE IF NOT EXISTS BeerCatalog (
    ID VARCHAR(255) PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Brewery VARCHAR(100),
    Type VARCHAR(100) NOT NULL,
    ABV DECIMAL(5, 2),
    IBU DECIMAL(5, 2),
    Description VARCHAR(500),
    AccountID VARCHAR(255),
    FOREIGN KEY (AccountID) REFERENCES Accounts(ID),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Reviews (
ID VARCHAR(255) PRIMARY KEY,
ParticipantID VARCHAR(255),
BeerID VARCHAR(255),
Rating INT NOT NULL,
Quantity DECIMAL(5, 2),
Comment VARCHAR(500),
CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (BeerID) REFERENCES BeerCatalog(ID),
FOREIGN KEY (ParticipantID) REFERENCES Participants(ID)
);

CREATE TABLE IF NOT EXISTS BeerContainer (
    ID VARCHAR(255) PRIMARY KEY,
    EventID VARCHAR(255),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EventID) REFERENCES Events(ID)
);

CREATE TABLE IF NOT EXISTS ContainerBeers (
    ContainerID VARCHAR(255),
    EventID VARCHAR(255),
    BeerID VARCHAR(255),
    Foreign KEY (ContainerID) REFERENCES BeerContainer(ID),
    Foreign KEY (EventID) REFERENCES Events(ID),
    Foreign KEY (BeerID) REFERENCES BeerCatalog(ID)
);

CREATE TABLE IF NOT EXISTS FavoriteBeers (
    BeerID VARCHAR(255),
    AccountID VARCHAR(255),
    FOREIGN KEY (BeerID) REFERENCES BeerCatalog(ID),
    FOREIGN KEY (AccountID) REFERENCES Accounts(ID)
);